In [28]:
import pandas as pd
pd.options.display.float_format = '{:.3f}'.format

In [29]:
df = pd.read_csv('resnet18_cfv8_results.csv', sep=',')
df.head()

  dataset loss  seed  best_acc  best_cmae  final_acc  final_cmae
0    cfv8   ce     0     0.880      0.208      0.897       0.178
1    cfv8   ce     1     0.887      0.190      0.887       0.190
2    cfv8   ce     2     0.892      0.164      0.892       0.164
3    cfv8   ce     3     0.914      0.133      0.866       0.256
4    cfv8   ce     4     0.891      0.196      0.891       0.196

In [30]:
groups = df.groupby('loss')[['best_acc', 'best_cmae', 'final_acc', 'final_cmae']].agg(['mean', 'std'])
groups

         best_acc       best_cmae       final_acc       final_cmae
             mean   std      mean   std      mean   std       mean   std
loss
ce          0.893 0.013     0.178 0.030     0.886 0.012      0.197 0.035
ce_msevl    0.903 0.011     0.149 0.029     0.894 0.009      0.171 0.034
eucvl       0.896 0.006     0.163 0.020     0.884 0.016      0.171 0.028
msevl       0.905 0.010     0.129 0.026     0.883 0.031      0.176 0.064
nsvl        0.864 0.015     0.214 0.044     0.680 0.235      0.506 0.450
svl         0.802 0.076     0.233 0.077     0.777 0.086      0.292 0.112
vmce        0.400 0.255     1.126 0.610     0.402 0.204      1.127 0.517
vmce_mu     0.480 0.227     0.925 0.537     0.377 0.249      1.185 0.576
vmsl_1      0.893 0.004     0.151 0.014     0.895 0.007      0.147 0.015
vmsl_2      0.911 0.006     0.116 0.013     0.902 0.006      0.129 0.020
vmsl_3      0.912 0.004     0.111 0.008     0.865 0.048      0.231 0.142
vmsl_4      0.905 0.004     0.130 0.010     0.882 0.021      0.175 0.042
vmsl_5      0.906 0.005     0.134 0.008     0.894 0.009      0.162 0.024

In [31]:
groups.xs('mean', axis=1, level=1)

          best_acc  best_cmae  final_acc  final_cmae
loss
ce           0.893      0.178      0.886       0.197
ce_msevl     0.903      0.149      0.894       0.171
eucvl        0.896      0.163      0.884       0.171
msevl        0.905      0.129      0.883       0.176
nsvl         0.864      0.214      0.680       0.506
svl          0.802      0.233      0.777       0.292
vmce         0.400      1.126      0.402       1.127
vmce_mu      0.480      0.925      0.377       1.185
vmsl_1       0.893      0.151      0.895       0.147
vmsl_2       0.911      0.116      0.902       0.129
vmsl_3       0.912      0.111      0.865       0.231
vmsl_4       0.905      0.130      0.882       0.175
vmsl_5       0.906      0.134      0.894       0.162

In [33]:
groups.style.format('{:.3f}').highlight_max(axis=0, subset=[('best_acc', 'mean'), ('final_acc', 'mean')], color='lightgreen').highlight_min(axis=0, subset=[('best_cmae', 'mean'), ('final_cmae', 'mean')], color='lightcoral')