In [2]:
import pandas as pd
pd.options.display.float_format = '{:.3f}'.format

In [3]:
df = pd.read_csv('resnet18_coil8_results.csv', sep=',')
df.head()

  dataset loss  seed  best_acc  best_cmae  final_acc  final_cmae
0   coil8   ce     0     0.843      0.219      0.825       0.245
1   coil8   ce     1     0.849      0.194      0.849       0.231
2   coil8   ce     2     0.818      0.242      0.845       0.225
3   coil8   ce     3     0.860      0.185      0.843       0.189
4   coil8   ce     4     0.839      0.214      0.859       0.183

In [4]:
groups = df.groupby('loss')[['best_acc', 'best_cmae', 'final_acc', 'final_cmae']].agg(['mean', 'std'])
groups

       best_acc       best_cmae       final_acc       final_cmae
           mean   std      mean   std      mean   std       mean   std
loss
ce        0.842 0.016     0.211 0.022     0.844 0.012      0.215 0.027
msevl     0.819 0.018     0.209 0.035     0.799 0.025      0.248 0.062
vmsl_1    0.832 0.012     0.183 0.023     0.823 0.016      0.195 0.025
vmsl_2    0.844 0.003     0.166 0.006     0.832 0.008      0.188 0.008
vmsl_3    0.856 0.003     0.154 0.007     0.812 0.068      0.246 0.137
vmsl_4    0.862 0.009     0.152 0.011     0.841 0.044      0.196 0.079
vmsl_5    0.858 0.007     0.158 0.012     0.821 0.069      0.242 0.163

In [5]:
groups.xs('mean', axis=1, level=1)

        best_acc  best_cmae  final_acc  final_cmae
loss
ce         0.842      0.211      0.844       0.215
msevl      0.819      0.209      0.799       0.248
vmsl_1     0.832      0.183      0.823       0.195
vmsl_2     0.844      0.166      0.832       0.188
vmsl_3     0.856      0.154      0.812       0.246
vmsl_4     0.862      0.152      0.841       0.196
vmsl_5     0.858      0.158      0.821       0.242

In [6]:
groups.style.format('{:.3f}').highlight_max(axis=0, subset=[('best_acc', 'mean'), ('final_acc', 'mean')], color='lightgreen').highlight_min(axis=0, subset=[('best_cmae', 'mean'), ('final_cmae', 'mean')], color='lightcoral')